import Head from "next/head";
import { useEffect } from "react";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";
import { setLoggedUser, useStateValue } from "../contexts";
import { LoggedUser } from "../types";

const Home = () => {
	const [state, dispatch] = useStateValue();
	const router = useRouter();

	console.log("Inside index");

	useEffect(() => {
		const loggedUser: LoggedUser = JSON.parse(
			localStorage.getItem("loggedUser") || "{}"
		);

		console.log("loggedUser: ", loggedUser);
		console.log("state.loggedUser: ", state.loggedUser);

		if (Object.keys(loggedUser).length === 0) {
			router.push("/login");
		}
		if (!state.loggedUser) {
			dispatch({
				type: "SET_LOGGED_USER",
				payload: loggedUser
			});
		} else {
			console.log(
				"!state.loggedUser in pages/index.tsx useEffect: ",
				state.loggedUser
			);
		}
		router.push("/feed");
	}, [state.loggedUser]);

	return (
		<div className={styles.container}>
			<Head>
				<title>MeetMax</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main} />

			<footer className={styles.footer}>Footer</footer>
		</div>
	);
};

export default Home;
